### ISSUE TITLE
debug-collector: collect ramoops data into BMC dump

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-debug-collector#15]
OpenBMC recently put in code to collect ramoops data  when a system kernel oops/panics. 

The data is written into /var/lib/systemd/pstore/ and would look like the following:

```
# ls /var/lib/systemd/pstore/
console-ramoops-0  dmesg-ramoops-0    dmesg-ramoops-1    dmesg.txt
```

@amboar may have some input on what to gather but I think in general the safest bet is to just grab everything in that directory, put it in a dump, and then delete everything in that directory.

FYI @ojayanth

**Comment by amboar** [comment]
> @amboar may have some input on what to gather but I think in general the safest bet is to just grab everything in that directory, put it in a dump, and then delete everything in that directory.

Yep, just grab everything.

**Comment by geissonator** [comment]
Easiest way I've found to test this is to build an image with the following commit:

https://gerrit.openbmc-project.xyz/c/openbmc/meta-aspeed/+/37820

Then trigger a kernel panic via this:
```echo c > /proc/sysrq-trigger```

**Comment by lxwinspur** [comment]
@geissonator 
I added `CONFIG_MAGIC_SYSRQ=y` to the `aspeed-g5` file, and still not found `/proc/sysrq-trigger` file.
Could u help me, or please correct me if I am wrong, Thanks :)

**Comment by geissonator** [comment]
@lxwinspur I've only added to the aspeed-g6 but I don't see why it wouldn't work for other platforms. Are you sure you applied it correctly to your build?

**Comment by ojayanth** [comment]
@amboar @geissonator @lxwinspur  Proposed flow for Kernel oops based dump

https://www.freedesktop.org/software/systemd/man/systemd-pstore.service.html Provides the details of managing systemd=pstore.service. 
Andrew J can comment on any additional work required to enable this , to copy the required contents into /var/lib/systemd/pstore/ 

BMC Dump creation for any new Kernel oops.
- Design direction should be introduce new dump type kernel-oops and implement infrastructure to enable new dump type similar “core” dump triggered during Application core.
- Create new service call “obmc-kernnel-oops-monitor.service” , used for managing Kernel-oops dump types
    - Design.
        - Update Create.interface.yaml with new Dump types
        - New Application to watch  “/var/lib/systemd/pstore/ “ folder updates.
        - Copy the folder contents to  Known place for packaging and delete the contents from pstore path
        - Add support  dreport  for new Dump types and packaging contents.
        - Updates dreport plugin to add additional data , like Journal log and any additional info if any. ( Refer  phosphor-debug-collector/tools/dreport.d/plugins.d  for existing plugins.)

**Comment by williamspatrick** [comment]
Does this really need a new dump type / Create interface / new application?  This is, as best I can tell, essentially a “core dump of the kernel”, so why not use the existing dump type we have for that and just monitor an additional location?

**Comment by amboar** [comment]
Yes, I was saying to @ojayanth that the proposal involved more complexity than I was expecting. If we can re-use an existing dump type then I'm all for that.

**Comment by ojayanth** [comment]
Currently "core"  dump type is used collect data for Application core  and the dump content is designed for debugging specific core issue , like journal log specific to PID of the core.  And PID information is collected from Systemd coredump  file ( file name provides the required details).  Also dump monitor service got dependency on systemd core dump package. In summary existing "core" type dump design is specific to manage systemd-core dump generated file. 

Kernel oops related dump behavior is different  based on the way it creates and content user is looking compare to application core. That is the reason am proposing new type and also providing capability to user to enable/disable this particular dump type easily. @amboar @williamspatrick

**Comment by amboar** [comment]
Right. Note that we're migrating from no kernel data captured through `ramoops` to `kdump`. `ramoops` is a transition step to work-around the current lack of `kexec` support required for `kdump`. It sounds like you'd want yet another dump type for `kdump`.

**Comment by ojayanth** [comment]
Since this is workaround. Proposed flow will help user to control this  feature easily. 
Also no impact in existing core dump flow.  
effort wise , not saving much with hacking existing core dump type to support this workaround.

**Comment by lxwinspur** [comment]
@williamspatrick @amboar 
Are there any questions to discuss?

Since I am not familiar with `kdump`, I want to get more suggestions.
Thanks.

**Comment by lxwinspur** [comment]
I asked @geissonator yesterday

```
those files will always be there before your service starts, it’s not like core dumps where they can randomly show up. 
All you really need to do is start the app and look for anything in that dir, if they are there, collect them all in a dump. 
No need to trigger on file creation events and such.

Basically system is up, a kernel panic occurs, the data is collected as the BMC is crashing. 
Once the BMC comes back up, the files will be in /var/lib/systemd/pstore/ before the service starts.
```

So, I think we do not need to watch any files, we only collect them once after the `ramoops` service started?

@williamspatrick @amboar @geissonator @ojayanth
Do you agree on this way? or please let me know if you have a better way.

Once the design finalized, I will update my code.

Thanks a lot :)

**Comment by amboar** [comment]
>  we only collect them once after the ramoops service started?

What do you mean by "ramoops service"? Do you mean `systemd-pstore.service`? Otherwise there's no service as such, it's just a behaviour that the kernel provides.

The operating concept was that the files would be captured into a dump during the BMC boot process. As long as what you have does that and the implementation isn't overly byzantine, then we've got what we want.

**Comment by lxwinspur** [comment]
> What do you mean by "ramoops service"? Do you mean systemd-pstore.service? Otherwise there's no service as such, it's just a behaviour that the kernel provides.

The original idea was to implement a ramoops service, refer: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41157.
I think we need it if we want to separate `ramoops data` and `core dump data`

And the `ramoops service` is only run once

**Comment by amboar** [comment]
> The original idea was to implement a ramoops service, refer: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41157.

Okay, this looks roughly like what we need.
