### ISSUE TITLE
ramoops dump create even when no ramoops files are present

### ISSUE THREAD

**Issue by geissonator** [openbmc/phosphor-debug-collector#16]
A HW CI machine started failing because it was seeing a dump present after every BMC reboot. After some digging, it looks like the issue is that the system has a /var/lib/systemd/pstore/ directory but there are no files in it. The new logic introduced in https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/40412 should ensure there is at least one file within the  /var/lib/systemd/pstore/  directory before requesting a dump.

The /var/lib/systemd/pstore/  dir is persistent so once a ramoops occurs, that directory will always be there. Need to ensure it has some files in it before generating a dump.

In this case, the dump is basically just empty:
```
# ls -al
drwxr-xr-x    2 root     root           100 Jul 26 15:59 .
drwxrwxrwt    9 root     root           200 Jul 26 16:11 ..
-rw-r--r--    1 root     root            74 Jul 26 15:56 dreport.log
-rw-r--r--    1 root     root           292 Jul 26 15:56 os-release
-rw-r--r--    1 root     root           289 Jul 26 15:56 summary.log

```

To recreate
```
mkdir /var/lib/systemd/pstore/
systemctl restart ramoops-monitor.service
```

**Comment by lxwinspur** [comment]
Hey @geissonator 

I do not think we need to create this file (`/var/lib/systemd/pstore`) manually.
Because this file is created by the following configuration: 
https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-kernel/linux/linux-aspeed/p10bmc.cfg#L10-L13

And in AST2500, they are set to `y` by default:
https://github.com/openbmc/linux/blob/dev-5.10/arch/arm/configs/aspeed_g5_defconfig#L300-L303

Please correct me if I am wrong, Thanks.

**Comment by ojayanth** [comment]
> Hey @geissonator
> 
> I do not think we need to create this file (`/var/lib/systemd/pstore`) manually.
> Because this file is created by the following configuration:
> https://github.com/openbmc/openbmc/blob/master/meta-ibm/recipes-kernel/linux/linux-aspeed/p10bmc.cfg#L10-L13
> 
> And in AST2500, they are set to `y` by default:
> https://github.com/openbmc/linux/blob/dev-5.10/arch/arm/configs/aspeed_g5_defconfig#L300-L303
> 
> Please correct me if I am wrong, Thanks.

@geissonator is recommending to add additional check in https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/40412/13/ramoops_manager.cpp#24 . Like trigger dump only if the directory contains any files. Current check alway's pass because only checking vector is empty or not.

**Comment by geissonator** [comment]
Looks like this was resolved by https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-debug-collector/+/47724
