### ISSUE TITLE
dreport: ramoops plugin doesn't validate optional_path

### ISSUE THREAD

**Issue by jeaaustx** [openbmc/phosphor-debug-collector#24]
The ramoops plugin for dreport copies all regular files from the $optional_path directory into the dump and removes them from the directory after the copy.

However, it does not confirm an optional_path has been set. If not set then it acts on the root filesystem. This filesystem was readonly but if that ever changes this could be a dangerous action for this command to take.

A simple check that optional_path is initialized should be performed before any work is done here. The corefile plugin shows an example of this RAS check.

**Comment by williamspatrick** [comment]
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/59185 ramoops: avoid deleting root [NEW]
